<?php 
return [
    'Auth'                  => ['CORE' => 1, 'CUSTOM' => 0],
    'Cliparts'              => ['CORE' => 1, 'CUSTOM' => 0],
    'Products'              => ['CORE' => 1, 'CUSTOM' => 0],
    // 'ColorSwatches'         => ['CORE' => 1, 'CUSTOM' => 0],
    // 'PrintAreas'            => ['CORE' => 1, 'CUSTOM' => 0],
    // 'PrintProfiles'         => ['CORE' => 1, 'CUSTOM' => 0],
    // 'ProductImageSides'     => ['CORE' => 1, 'CUSTOM' => 0],
    // 'PrintAreaTypes'        => ['CORE' => 1, 'CUSTOM' => 0],
    // 'ProductDecorations'    => ['CORE' => 1, 'CUSTOM' => 0],
    'Fonts'                 => ['CORE' => 1, 'CUSTOM' => 0],
    // 'Colors'                => ['CORE' => 1, 'CUSTOM' => 0],
    'Distresses'            => ['CORE' => 1, 'CUSTOM' => 0],
    // 'GraphicFonts'          => ['CORE' => 1, 'CUSTOM' => 0],
    'Masks'                 => ['CORE' => 1, 'CUSTOM' => 0],
    'Shapes'                => ['CORE' => 1, 'CUSTOM' => 0],
    'Backgrounds'           => ['CORE' => 1, 'CUSTOM' => 0],
    'WordClouds'            => ['CORE' => 1, 'CUSTOM' => 0],
    'Customers'             => ['CORE' => 1, 'CUSTOM' => 0],
    'Orders'                => ['CORE' => 1, 'CUSTOM' => 0],
    'PrintProfiles'         => ['CORE' => 1, 'CUSTOM' => 0],
    'ColorPalletes'         => ['CORE' => 1, 'CUSTOM' => 0],
    'DecorationAreas'       => ['CORE' => 1, 'CUSTOM' => 0],
    'Settings'              => ['CORE' => 1, 'CUSTOM' => 0],
    // 'OrderLogs'             => ['CORE' => 1, 'CUSTOM' => 0],
    // 'ColorVariants'         => ['CORE' => 1, 'CUSTOM' => 0],
    // 'ColorTypes'            => ['CORE' => 1, 'CUSTOM' => 0],
];