<?php 
return [
    'Auth'                  => ['CORE' => true, 'CUSTOM' => false],
    'Cliparts'              => ['CORE' => true, 'CUSTOM' => false],
    'Products'              => ['CORE' => true, 'CUSTOM' => false],
    'ColorSwatches'         => ['CORE' => true, 'CUSTOM' => false],
    'PrintAreas'            => ['CORE' => true, 'CUSTOM' => false],
    // 'PrintProfiles'         => ['CORE' => true, 'CUSTOM' => false],
    'ProductImageSides'     => ['CORE' => true, 'CUSTOM' => false],
    'PrintAreaTypes'        => ['CORE' => true, 'CUSTOM' => false],
    'ProductDecorations'    => ['CORE' => true, 'CUSTOM' => false],
    'Fonts'                 => ['CORE' => true, 'CUSTOM' => false],
    // 'Colors'                => ['CORE' => true, 'CUSTOM' => false],
    'Distresses'            => ['CORE' => true, 'CUSTOM' => false],
    // 'GraphicFonts'          => ['CORE' => true, 'CUSTOM' => false],
    'Masks'                 => ['CORE' => true, 'CUSTOM' => false],
    'Shapes'                => ['CORE' => true, 'CUSTOM' => false],
    'Backgrounds'    => ['CORE' => true, 'CUSTOM' => false],
    'WordClouds'            => ['CORE' => true, 'CUSTOM' => false],
    'Customers'             => ['CORE' => true, 'CUSTOM' => false],
    'Orders'                => ['CORE' => true, 'CUSTOM' => false],
    // 'OrderLogs'             => ['CORE' => true, 'CUSTOM' => false],
    // 'ColorVariants'         => ['CORE' => true, 'CUSTOM' => false],
    // 'ColorTypes'            => ['CORE' => true, 'CUSTOM' => false],
];
